# Defaults globales
default_image: ros:humble
default_root: /work
default_pattern: "*_ws"
default_depth: 2
default_order: bottomup
gpus: false
entrypoint_path: "~/.config/cdocker/entrypoint.sh"

# Variables de entorno comunes
env:
  LANG: C.UTF-8
  RMW_IMPLEMENTATION: rmw_fastrtps_cpp

# Montajes adicionales (formato Docker --mount)
mounts:
  - "type=bind,src=$HOME/.colcon,dst=/root/.colcon"
  - "type=bind,src=$HOME/.cache/ccache,dst=/root/.cache/ccache"

# Perfiles (opcional; tu CLI podría usarlos en el futuro)
profiles:
  humble:
    image: ros:humble
  iron:
    image: ros:iron
